# Generated by Django 5.2.8 on 2026-09-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vip", "0017_voiceconversation_is_muted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voiceconversation",
            name="is_paused",
        ),
    ]
